### ISSUE TITLE
Always check UBA status before start torrent download

### ISSUE THREAD

**Issue by bclermont** [UnblockApp/qbittorrent#8] opened 2015-07-01 06:57 UTC
When I encounter https://github.com/UnblockApp/unblockapp-win/issues/30 issue, I found that I could just click download and it just didn't connect.

My guess is that VPN Connection only occurs at *startup*.

Is there a way to perform such validation everywhere/anywhere it need to go online?

**Comment by bclermont** [comment] 2015-10-06 08:27
@mogikanin as Oriane asked more than 2 months ago:

> @mogikanin : is this done?

**Comment by mogikanin** [comment] 2015-10-06 08:53
@bclermont , at the moment there is an option in QBT settings for enable\disable VPN. In case when option is checked (by default), the QBT connects to VPN. And yes, in case when option is checked, qbt connects to VPN on startup.

**Comment by mogikanin** [comment] 2015-10-06 08:58
looks like duplicate of https://github.com/UnblockApp/qbittorrent/issues/10

**Comment by bclermont** [comment] 2015-10-06 10:10
> looks like duplicate of #10

@mogikanin somewhat related but not the same, in the case of #10 the VPN connection failed but download still run. while this task is before trigger any new upload

**Comment by bclermont** [comment] 2015-10-06 10:14
> what you mean?

what I men is that #10 is VPN is connected, qbt download torrent.
VPN stopped/disconnect/fail
download don't stop

#8 is: qbt don't download anything.
someone click something to download a torrent
qbt must check it's properly connected to VPN before really downloading

**Closed** 2015-10-07 09:50 UTC
